prjCooking/Controllers/ManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using prjCooking.Models;
using prjCooking.ViewModel;

namespace prjCooking.Controllers
{
    public class ManagerController : Controller
    {
        public ActionResult query檢舉()
        {
            dbCookingEntities db = new dbCookingEntities();
            var query檢舉 = (from prod in db.t檢舉
                           select prod.f被檢舉的聚會Id).Distinct().ToList();

            IEnumerable<t聚會> datas = null;
            int id = 0;
            List<C管理者聚會ViewModel> Plist = new List<C管理者聚會ViewModel>();
            string keyword = Request.Form["txtKeyword"];
            if (string.IsNullOrEmpty(keyword))
            {
                foreach (int m in query檢舉)
                {
                    //m.f被檢舉的聚會Id = id;
                    datas = (from p in (new dbCookingEntities()).t聚會 where p.f聚會Id == m select p);
                    //聚會資料放進viewmodel
                    foreach (t聚會 p in datas)
                    {
                        Plist.Add(new C管理者聚會ViewModel() { party = p });

                    }
                }
            }
            else
            {
                datas = from p in (new dbCookingEntities()).t聚會 where p.f聚會名稱.Contains(keyword) select p;
                foreach (t聚會 p in datas)
                {
                    Plist.Add(new C管理者聚會ViewModel() { party = p });

                }
            }
                

            

        

            //修正部分viewmodel顯示資訊
            foreach (C管理者聚會ViewModel p in Plist)
            {
                t會員 member = (new dbCookingEntities()).Cooking查詢某會員的資料By會員Id(p.f主辦人);

                t檢舉 query檢舉p = new t檢舉();
                query檢舉p = db.t檢舉.FirstOrDefault(m => m.f被檢舉的聚會Id == p.f聚會Id);

                p.聚會建立日期 = Convert.ToDateTime(p.f聚會建立日期).ToShortDateString();

                p.煮辦人姓名 = member.f會員姓名;

                string party狀態;
                if (p.f聚會狀態 == Convert.ToInt32(聚會狀態.可報名))
                    party狀態 = "可報名";
                else if (p.f聚會狀態 == Convert.ToInt32(聚會狀態.進行中))
                    party狀態 = "進行中";
                else
                    party狀態 = "已結束";
                p.聚會狀態 = party狀態;
                if (p.f聚會垃圾桶 == false)
                    p.聚會垃圾桶 = " ";
                else
                    p.聚會垃圾桶 = "✘";

                if (query檢舉p != null)
                {

                  
                        p.聚會檢舉狀態顯示 = "已檢舉";

                }
                else
                {
                    p.聚會檢舉狀態顯示 = " ";

                }

            }
            return View(Plist);
        }
        public ActionResult 檢舉頁面(int? id)
        {
            ViewBag.f聚會id = id;
            dbCookingEntities db = new dbCookingEntities();
            t檢舉 query檢舉 = new t檢舉();
            query檢舉 = db.t檢舉.FirstOrDefault(m => m.f被檢舉的聚會Id == id);
            if (query檢舉 != null)
            {
                ViewBag.f檢舉日期 = query檢舉.f檢舉建立日期;
                ViewBag.f檢舉原因 = query檢舉.f檢舉原因;
            }
               
            return View();
        }
        public ActionResult 下架檢舉的活動(int? id)
        {
            
            (new C聚會相關操作()).取消檢舉聚會(id.Value);
            dbCookingEntities db = new dbCookingEntities();
            var query檢舉 = (from prod in db.t檢舉
                           where prod.f被檢舉的聚會Id == id
                           select prod).ToList();


            foreach (t檢舉 p in query檢舉)
            {
                //p.f檢舉原因 = DateTime.Today.ToString()+"已處理";
                db.t檢舉.Remove(p);
                db.SaveChanges();
            }


            return RedirectToAction("PartyList");

        }
        public ActionResult no下架檢舉的活動(int? id)
        {
            dbCookingEntities db = new dbCookingEntities();
            var query檢舉 = (from prod in db.t檢舉
                           where prod.f被檢舉的聚會Id == id
                           select prod).ToList();


            foreach (t檢舉 p in query檢舉)
            {
                //p.f檢舉原因 = DateTime.Today.ToString()+"已處理";
                db.t檢舉.Remove(p);
                db.SaveChanges();
            }

            return RedirectToAction("PartyList");

        }

        // GET: Manager
        public ActionResult PartyList()
        {
            IEnumerable<t聚會> datas = null;
            string keyword = Request.Form["txtKeyword"];
            if (string.IsNullOrEmpty(keyword))
                datas = from p in (new dbCookingEntities()).t聚會 select p;
            else
                datas = from p in (new dbCookingEntities()).t聚會 where p.f聚會名稱.Contains(keyword) select p;

            List<C管理者聚會ViewModel> Plist = new List<C管理者聚會ViewModel>();

            //聚會資料放進viewmodel
            foreach (t聚會 p in datas)
            {
                Plist.Add(new C管理者聚會ViewModel() { party = p });

            }
            //修正部分viewmodel顯示資訊
            foreach (C管理者聚會ViewModel p in Plist)
            {
                t會員 member = (new dbCookingEntities()).Cooking查詢某會員的資料By會員Id(p.f主辦人);
                dbCookingEntities db = new dbCookingEntities();
                t檢舉 query檢舉 = new t檢舉();
                query檢舉 = db.t檢舉.FirstOrDefault(m => m.f被檢舉的聚會Id == p.f聚會Id);

                p.聚會建立日期 = Convert.ToDateTime(p.f聚會建立日期).ToShortDateString();

                p.煮辦人姓名 = member.f會員姓名;

                string party狀態;
                if (p.f聚會狀態 == Convert.ToInt32(聚會狀態.可報名))
                    party狀態 = "可報名";
                else if (p.f聚會狀態 == Convert.ToInt32(聚會狀態.進行中))
                    party狀態 = "進行中";
                else
                    party狀態 = "已結束";
                p.聚會狀態 = party狀態;
                if (p.f聚會垃圾桶 == false)
                    p.聚會垃圾桶 = " ";
                else
                    p.聚會垃圾桶 = "✘";

                if (query檢舉 != null)
                {                
                        p.聚會檢舉狀態顯示 = "已檢舉";
                }
                else
                {
                    p.聚會檢舉狀態顯示 = " ";
                }



            }


            return View(Plist);
        }
        public ActionResult Details(int id,string 權限,string 性別)
        {
 
            dbCookingEntities db = new dbCookingEntities();
            t會員 member_select = db.t會員.FirstOrDefault(p => p.f會員Id == id);
            if (member_select == null)
                return RedirectToAction("List");

            return View(new C管理者會員ViewModel() { member = member_select });

        }
        public ActionResult Delete(int id)
        {
            dbCookingEntities db = new dbCookingEntities();
            t會員 member_select = db.t會員.FirstOrDefault(p => p.f會員Id == id);
            if (member_select != null)
            {
                db.t會員.Remove(member_select);
                db.SaveChanges();
            }
            return RedirectToAction("List");
        }
        public ActionResult List()
        {
            dbCookingEntities db = new dbCookingEntities();
            IEnumerable<t會員> datas = null;
            string keyword = Request.Form["txtKeyword"];
            if (string.IsNullOrEmpty(keyword))
                datas = from p in (new dbCookingEntities()).t會員 select p;
            else
                datas = from p in (new dbCookingEntities()).t會員 where p.f會員姓名.Contains(keyword) || p.f會員信箱.Contains(keyword) select p;


            List<C管理者會員ViewModel> list = new List<C管理者會員ViewModel>();
            foreach (t會員 p in datas)
                list.Add(new C管理者會員ViewModel() { member = p });

            //修正部分viewmodel顯示資訊
            foreach (C管理者會員ViewModel p in list)
            {
                string a = p.f會員建立日期.ToString("yyyy/MM/dd");
                p.會員建立日期= a;
                if (p.f性別 == 0)
                    p.性別 = "不公開";
                else if (p.f性別 == 1)
                    p.性別 = "男";
                else
                    p.性別 = "女";

                if (p.f權限 == 1)
                    p.權限 = "管理者";
                else if (p.f權限 == 2)
                    p.權限 = "黑名單";
                else
                    p.權限 = "一般會員";

                p.檢舉下架次數 = db.Cooking查詢某會員被檢舉下架的聚會ListBy會員Id(p.f會員Id);

                
                   
            
                
            }


            return View(list);

        }
        public ActionResult 用戶恢復(int id)
        {
            (new C聚會相關操作()).恢復會員權限(id);
            return RedirectToAction("List");
        }
        public ActionResult 用戶停權(int id)
        {
            (new C聚會相關操作()).修改會員權限(id);
            return RedirectToAction("List");
        }
        public ActionResult query黑名單()
        {
            dbCookingEntities db = new dbCookingEntities();
            IEnumerable<t會員> datas = null;
            string keyword = Request.Form["txtKeyword"];
            if (string.IsNullOrEmpty(keyword))
                datas = from p in (new dbCookingEntities()).t會員 where p.f權限==2 select p;
            else
                datas = from p in (new dbCookingEntities()).t會員 where p.f會員姓名.Contains(keyword) || p.f會員信箱.Contains(keyword) select p;


            List<C管理者會員ViewModel> list = new List<C管理者會員ViewModel>();
            foreach (t會員 p in datas)
                list.Add(new C管理者會員ViewModel() { member = p });

            //修正部分viewmodel顯示資訊
            foreach (C管理者會員ViewModel p in list)
            {
                string a = p.f會員建立日期.ToString("yyyy/MM/dd");
                p.會員建立日期 = a;
                if (p.f性別 == 0)
                    p.性別 = "不公開";
                else if (p.f性別 == 1)
                    p.性別 = "男";
                else
                    p.性別 = "女";

                if (p.f權限 == 1)
                    p.權限 = "管理者";
                else
                    p.權限 = "一般會員";

                p.檢舉下架次數 = db.Cooking查詢某會員被檢舉下架的聚會ListBy會員Id(p.f會員Id);

                if (p.檢舉下架次數.Count >= 3)
                {
                    (new C聚會相關操作()).修改會員權限(p.f會員Id);
                }

            }

prjCooking/Views/Manager/Details.cshtml
@model prjCooking.ViewModel.C管理者會員ViewModel

@{
    ViewBag.Title = "會員資訊";
}



@using (Html.BeginForm("Details", "Manager",
    FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <h2>編輯個人資訊</h2>
    <hr />

    @Html.AntiForgeryToken()

    <aside class="container ">
        <aside class="row">
            <aside class="col-md-6 offset-md-1 text-center bg-light">

                <!-- 開始編輯資訊 -->
                <div class="form-horizontal row">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <aside class=" col-12 text-left">

                        <!--照片-->
                        <div class="form-group">
                            <br />
                            <img src="~/Image/@Model.f會員照片" id="imgpreview" class="rounded-circle " width="170" height="170" />
                            <br />

                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.權限, htmlAttributes: new { @class = "control-label" })

                            @Html.EditorFor(model => model.權限, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                            @Html.ValidationMessageFor(model => model.權限, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.f會員姓名, htmlAttributes: new { @class = "control-label" })

                            @Html.EditorFor(model => model.f會員姓名, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                            @Html.ValidationMessageFor(model => model.f會員姓名, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.性別, htmlAttributes: new { @class = "control-label" })

                            @Html.EditorFor(model => model.性別, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                            @Html.ValidationMessageFor(model => model.性別, "", new { @class = "text-danger" })

                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.f會員信箱, htmlAttributes: new { @class = "control-label" })

                            @Html.EditorFor(model => model.f會員信箱, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                            @Html.ValidationMessageFor(model => model.f會員信箱, "", new { @class = "text-danger" })

                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.f會員密碼, htmlAttributes: new { @class = "control-label" })

                            @Html.EditorFor(model => model.f會員密碼, new { htmlAttributes = new { @class = "form-control", @type = "password", disabled = "disabled" } })
                            @Html.ValidationMessageFor(model => model.f會員密碼, "", new { @class = "text-danger" })

                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.f自我介紹, htmlAttributes: new { @class = "control-label" })

                            @Html.EditorFor(model => model.f自我介紹, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                            @Html.ValidationMessageFor(model => model.f自我介紹, "", new { @class = "text-danger" })

                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.f會員電話, htmlAttributes: new { @class = "control-label" })

                            @Html.EditorFor(model => model.f會員電話, new { htmlAttributes = new { @class = "form-control", style = "width:50%", disabled = "disabled" } })
                            @Html.ValidationMessageFor(model => model.f會員電話, "", new { @class = "text-danger" })

                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.f會員建立日期, htmlAttributes: new { @class = "control-label" })

                            @Html.EditorFor(model => model.f會員建立日期, new { htmlAttributes = new { @class = "form-control", style = "width:50%", disabled = "disabled" } })
                            @Html.ValidationMessageFor(model => model.f會員建立日期, "", new { @class = "text-danger" })

                        </div>
                    </aside>
                    <aside class="col-12 text-right">
                        <div class="form-group">
                            <br />
                            <a href="~/Member/Show個人頁面/@Model.f會員Id">
                                <input type="button" class = "btn btn-outline-info" value="個人頁面" />
                            </a>

                            @Html.ActionLink("返回用戶列表", "List", new { id = @Model.f會員Id }, new { Class = "btn btn-outline-info" })


                        </div>
                    </aside>
                </div>
            </aside>
        </aside>
    </aside>


}



<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

prjCooking/Views/Manager/List.cshtml
@using prjCooking.ViewModel;
@model List<C管理者會員ViewModel>

@{
    ViewBag.Title = "用戶管理";
}
<section class="service-wrapper py-7">
    <div class="service-tag py-5 bg-white">
    </div>
</section>

<h2 class="text-info">用戶管理</h2>

<hr>
<br>

@using (Html.BeginForm())
{
<section>
    <div class="container ">
        <div class="row">
            <div class="col-12 text-left">
                @Html.ActionLink("回到用戶列表", "List", "Manager", new { Class = "btn btn-sm btn-secondary" })
                <br /><br />
                <label>用戶查詢:</label>

                <br />

            </div>
            <div class="col-12 text-left">
                <input class="form-control" type="text" placeholder="請輸入帳號、姓名" name="txtKeyword" style="width:50%">
                  <br />
                <input class="btn btn-sm btn-info" type="submit" value="查詢" />
          
                <br />
                
                <br /><br />
            </div>
            
           
        </div>
            </div>

</section>
}


<table class="table  table-sm table-hover">
    <thead class="thead-light">
    <th class="col-md-1">
        序號
    </th>
    <th class="col-md-1">
       黑名單
        
    </th>
    <th class="col-md-2">
        @Html.DisplayNameFor(model => model[0].權限)
    </th>
    <th class="col-md-2">
        @Html.DisplayNameFor(model => model[0].f會員信箱)

    </th>

    <th class="col-md-2">
        @Html.DisplayNameFor(model => model[0].f會員姓名)
    </th>

    <th class="col-md-2">

        @Html.DisplayNameFor(model => model[0].f會員建立日期)

    </th>
    <th class="col-md-2"></th>
    </thead>

    @{ int count = 0;

        foreach (var item in Model)
        {
            count++;
            <tr>
                <td>
                    @count
                </td>
                <td>
                    @if ((item.檢舉下架次數.Count >= 3) && (item.f權限 == 0))
                    {

                        <input type="button" class="btn btn-sm" value="⚠" data-toggle="modal" data-target="#modalone1" />
                        <div class="modal text-center" id="modalone1">
                            <div class="modal-md modal-dialog modal-dialog-scrollable">

                                <div class="modal-content">
                                    <div class="modal-header">

                                        <img src="~/Image/heart.svg" class="modal-title">
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    </div>
                                    <div class="modal-body">
                                        <p>此用戶被檢舉成功次數已達3次，請確認是否要加入黑名單</p>

                                    </div>
                                    <div class="modal-footer">
                                        <input type="button" value="取消" class="btn btn-sm btn-outline-info" data-dismiss="modal">
                                        @Html.ActionLink("確定", "用戶停權", new { id = item.f會員Id }, new { Class = "btn btn-sm  btn-outline-info" })

                                    </div>
                                </div>
                            </div>
                        </div>

                    }
                    else if (item.f權限 == 2)
                    {
                        <input type="button" class="btn btn-sm btn-outline-danger" value="白名單" data-toggle="modal" data-target="#modalone2" />
                        <div class="modal text-center" id="modalone2">
                            <div class="modal-md modal-dialog modal-dialog-scrollable">

                                <div class="modal-content">
                                    <div class="modal-header">

                                        <img src="~/Image/heart.svg" class="modal-title">
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    </div>
                                    <div class="modal-body">
                                        <p>請確認是否要恢復此用戶的會員權限</p>

                                    </div>
                                    <div class="modal-footer">
                                        <input type="button" value="取消" class="btn btn-sm btn-outline-info" data-dismiss="modal">
                                        @Html.ActionLink("確定", "用戶恢復", new { id = item.f會員Id }, new { Class = "btn btn-sm  btn-outline-info" })

                                    </div>
                                </div>
                            </div>
                        </div>
                    }

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.權限)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.f會員信箱)
                </td>

                <td>
                   
                        @Html.DisplayFor(modelItem => item.f會員姓名)
                   
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.會員建立日期)
                </td>
                <td>

                    @Html.ActionLink("查看", "Details", "Manager", new { id = item.f會員Id,權限=item.權限,性別=item.性別 }, new { Class = "btn btn-sm btn-outline-secondary" })
                    @*@Html.ActionLink("刪除", "Delete", "Manager", new { id = item.f會員Id }, new { onclick = "return confirm('確定要刪除嗎?')", Class = "btn btn-sm btn-outline-secondary" })*@
                </td>
            </tr>
        }
    }
</table>
<br />

prjCooking/Views/Manager/PartyList.cshtml
@using prjCooking.ViewModel;
@using prjCooking.Models
@model List<C管理者聚會ViewModel>

@{
    ViewBag.Title = "聚會管理";
}
<style>
    .party_btn {
        cursor: pointer;
        transition: all 0.4s;
    }

        .party_btn:hover {
            transform: rotate(+45deg);
        }
</style>
<section class="service-wrapper py-7">
    <div class="service-tag py-5 bg-white">
    </div>
</section>

<h2 class="text-info">聚會管理</h2>
<hr>
<br>

@using (Html.BeginForm())
{
    <section>
        <div class="container ">
            <div class="row">
                <div class="col-12 text-left">
                    @Html.ActionLink("回到聚會列表", "PartyList", null, new { @class = "btn btn-sm btn-secondary" })

                    <br /><br />
                    <label>聚會查詢:</label>
                    <input class="form-control" type="text" placeholder="請輸入欲查詢的聚會名稱" style="width:50%" name="txtKeyword">
                    <br />
                </div>
                <div class="col-12 text-left">
                    <input class="btn btn-sm btn-info" type="submit" value="查詢" />
                    <br /><br />
                  <br />
                </div>


            </div>
        </div>
    </section>
}

<table class="table table-sm table-hover table-condensed">
    <thead class="thead-light">
    <th>
        序
    </th>
    <th>
        @Html.ActionLink("🚨", "query檢舉", null, new { @class = "party_btn btn btn-sm" })
    </th>
    <th>
        @Html.DisplayNameFor(model => model[0].聚會狀態)
    </th>
    <th>
        @Html.DisplayNameFor(model => model[0].聚會建立日期)
    </th>
    <th>
        @Html.DisplayNameFor(model => model[0].煮辦人姓名)
    </th>

    <th>
        @Html.DisplayNameFor(model => model[0].f聚會名稱)
    </th>





    <th>
    </th>
    </thead>

    @{
        int 主辦人id = 0;
        int count = 0;
        foreach (var item in Model)
        {
            主辦人id = item.f主辦人;
            count++;
        <tr>
            <td>
                @count

            </td>
            <td>
                @if ((item.f聚會垃圾桶 == false) && (item.聚會檢舉狀態顯示 == "已檢舉"))
                {
                    @Html.ActionLink("🚨", "檢舉頁面", new { id = item.f聚會Id }, new { Class = "party_btn btn btn-sm" })

                }
                else
                {
                    <p></p>
                }

            </td>
            <td>
                @if ((item.f聚會垃圾桶 == true) && (item.f聚會狀態 == 5))
                {
                    <p>檢舉下架</p>
                    
                }
                else if (item.f聚會垃圾桶 == true)
                {
                    <p>已下架</p>
                }
                else
                {
                    <p></p>
                }

            </td>

            <td>
                @Html.DisplayFor(modelItem => item.聚會建立日期)
            </td>
            <td>

                @Html.DisplayFor(modelItem => item.煮辦人姓名)


            </td>
            <td>
                @Html.DisplayFor(modelItem => item.f聚會名稱)
            </td>


            <td>

                @Html.ActionLink("查看", "showParty", "Meet", new { id = item.f聚會Id }, new { @class = "btn btn-sm btn-outline-secondary" })
                @*@Html.ActionLink("編輯", "Edit", new { id = item.f聚會Id }, new { @class = "btn btn-sm btn-outline-secondary" })*@

            </td>
        </tr>
        }
    }
</table>

prjCooking/Views/Manager/query檢舉.cshtml
@using prjCooking.ViewModel;
@using prjCooking.Models
@model List<C管理者聚會ViewModel>

@{
    ViewBag.Title = "聚會管理";
}
<style>
    .party_btn {
        cursor: pointer;
        transition: all 0.4s;
    }

        .party_btn:hover {
            transform: rotate(+45deg);
        }
</style>
<section class="service-wrapper py-7">
    <div class="service-tag py-5 bg-white">
    </div>
</section>

<h2 class="text-info">聚會管理</h2>
<hr>
<br>

@using (Html.BeginForm())
{
    <section>
        <div class="container ">
            <div class="row">
                <div class="col-12 text-left">
                    @Html.ActionLink("回到聚會列表", "PartyList", null, new { @class = "btn btn-sm btn-secondary" })
                    <br /><br />
                    <label>聚會查詢:</label>
                    <input class="form-control" type="text" placeholder="請輸入欲查詢的聚會名稱" style="width:50%" name="txtKeyword">
                    <br />
                </div>
                <div class="col-12 text-left">

                    <input class="btn btn-sm btn-info" type="submit" value="查詢" />
                    <br /><br />
                    <br />
                </div>


            </div>
        </div>
    </section>
}

<table class="table table-sm table-hover table-condensed">
    <thead class="thead-light">
    <th>
        序
    </th>
    <th>
        @Html.ActionLink("🚨", "query檢舉", null, new { @class = "party_btn btn btn-sm" })
    </th>
    <th>
        @Html.DisplayNameFor(model => model[0].聚會建立日期)
    </th>
    <th>
        @Html.DisplayNameFor(model => model[0].煮辦人姓名)
    </th>

    <th>
        @Html.DisplayNameFor(model => model[0].f聚會名稱)
    </th>

    <th>
        @Html.DisplayNameFor(model => model[0].聚會狀態)
    </th>



    <th>
    </th>
    </thead>

    @{
        int 主辦人id = 0;
        int count = 0;
        foreach (var item in Model)
        {
            主辦人id = item.f主辦人;
            count++;
            <tr>
                <td>
                    @count

                </td>
                <td>
                    @if ((item.f聚會垃圾桶 == false) && (item.聚會檢舉狀態顯示 == "已檢舉"))
                    {
                        @Html.ActionLink("🚨", "檢舉頁面", new { id = item.f聚會Id }, new { Class = "party_btn btn btn-sm" })

                    }
                    else
                    {
                        <p></p>
                    }

                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.聚會建立日期)
                </td>
                <td>

                    @Html.DisplayFor(modelItem => item.煮辦人姓名)


                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.f聚會名稱)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.聚會狀態)
                </td>


                <td>

                    @Html.ActionLink("查看", "showParty", "Meet", new { id = item.f聚會Id }, new { @class = "btn btn-sm btn-outline-secondary" })
                    @*@Html.ActionLink("編輯", "Edit", new { id = item.f聚會Id }, new { @class = "btn btn-sm btn-outline-secondary" })*@

                </td>
            </tr>
        }
    }
</table>

prjCooking/Views/Manager/query黑名單.cshtml
@using prjCooking.ViewModel;
@model List<C管理者會員ViewModel>

@{
    ViewBag.Title = "用戶管理";
}
<section class="service-wrapper py-7">
    <div class="service-tag py-5 bg-white">
    </div>
</section>

<h2 class="text-info">用戶管理</h2>

<hr>
<br>

@using (Html.BeginForm())
{
    <section>
        <div class="container ">
            <div class="row">
                <div class="col-12 text-left">
                    @Html.ActionLink("回到用戶列表", "List", "Manager", new { Class = "btn btn-sm btn-secondary" })
                    <br /><br />
                    <label>用戶查詢:</label>

                    <br />

                </div>
                <div class="col-12 text-left">
                    <input class="form-control" type="text" placeholder="請輸入帳號、姓名" name="txtKeyword" style="width:50%">
                    <br />
                    <input class="btn btn-sm btn-info" type="submit" value="查詢" />

                    <br />

                    <br /><br />
                </div>


            </div>
        </div>

    </section>
}


<table class="table  table-sm table-hover">
    <thead class="thead-light">
    <th class="col-md-1">
        序號
    </th>
    <th class="col-md-1">
        @Html.ActionLink("黑名單", "query黑名單", null, new { @class = "btn btn-sm btn-secondary" })

    </th>
    <th class="col-md-2">
        @Html.DisplayNameFor(model => model[0].權限)
    </th>
    <th class="col-md-2">
        @Html.DisplayNameFor(model => model[0].f會員信箱)

    </th>

    <th class="col-md-2">
        @Html.DisplayNameFor(model => model[0].f會員姓名)
    </th>

    <th class="col-md-2">

        @Html.DisplayNameFor(model => model[0].f會員建立日期)

    </th>
    <th class="col-md-2"></th>
    </thead>

    @{ int count = 0;

        foreach (var item in Model)
        {
            count++;
            <tr>
                <td>
                    @count
                </td>
                <td>
                    @if (item.檢舉下架次數.Count >= 3)
                    {
                        <p>⚠</p>

                    }

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.權限)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.f會員信箱)
                </td>

                <td>

                    @Html.DisplayFor(modelItem => item.f會員姓名)

                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.會員建立日期)
                </td>
                <td>

                    @Html.ActionLink("查看", "Details", "Manager", new { id = item.f會員Id, 權限 = item.權限, 性別 = item.性別 }, new { Class = "btn btn-sm btn-outline-secondary" })
                    @*@Html.ActionLink("刪除", "Delete", "Manager", new { id = item.f會員Id }, new { onclick = "return confirm('確定要刪除嗎?')", Class = "btn btn-sm btn-outline-secondary" })*@
                </td>
            </tr>
        }
    }
</table>
<br />