prjCooking/Controllers/FoodController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using prjCooking.Models;
using prjCooking.ViewModel;

namespace prjCooking.Controllers
{
    public class FoodController : Controller
    {
        // GET: Food
        public ActionResult Index()
        {

            return View();
        }
        public ActionResult queryCreateFood(int id)
        {
            dbCookingEntities db = new dbCookingEntities();

            int query主辦人id = ((t會員)Session[CSessionKey.登入會員_t會員]).f會員Id;
            var query聚會id = (from prod in db.t聚會
                             where prod.f主辦人 == query主辦人id
                             select prod.f聚會Id==id);
            ViewBag.Boss = query主辦人id;
            ViewBag.Partyid = id;
            return View();
        }
        [HttpPost]
        public ActionResult queryCreateFood(CFoodViewModel query聚會food)
        {
            dbCookingEntities db = new dbCookingEntities();

            t建議食材 addfood = new t建議食材();

            addfood.f聚會Id = Convert.ToInt32(Request.Form["f聚會Id"]);
            addfood.f食材名稱 = query聚會food.f食材名稱;
            addfood.f數量 = Convert.ToInt32(query聚會food.f數量);
            addfood.f單位 = query聚會food.f單位;

            db.t建議食材.Add(addfood);

            db.SaveChanges();

            return RedirectToAction("queryFoodList",new { id= query聚會food.f聚會Id});
        }
        public ActionResult queryEditFood(int id)
        {
            dbCookingEntities db = new dbCookingEntities();
            t建議食材 prod = db.t建議食材.FirstOrDefault(p => p.f建議食材Id == id);


            if (prod == null)
                return RedirectToAction("queryFoodList");

            return View(new CFoodViewModel() { party_food = prod });

        }
        [HttpPost]
        public ActionResult queryEditFood(CFoodViewModel editfood)
        {
            dbCookingEntities db = new dbCookingEntities();
            t建議食材 prod = db.t建議食材.FirstOrDefault(p => p.f建議食材Id == editfood.f建議食材Id);
            
            if (prod != null)
            {
               
                    prod.f聚會Id = Convert.ToInt32(Request.Form["f聚會Id"]);
                    prod.f食材名稱 = editfood.f食材名稱;
                    prod.f數量 = editfood.f數量;
                    prod.f單位 = editfood.f單位;

                    db.SaveChanges();
               
        
                
            }

            return RedirectToAction("queryFoodList",new { id=prod.f聚會Id});


        }

        public ActionResult EditFood(int id)
        {
            dbCookingEntities db = new dbCookingEntities();
            t建議食材 prod = db.t建議食材.FirstOrDefault(p => p.f建議食材Id == id);


            if (prod == null)
                return RedirectToAction("FoodList");

            return View(new CFoodViewModel() { party_food = prod });

        }
        [HttpPost]
        public ActionResult EditFood(CFoodViewModel editfood)
        {
            dbCookingEntities db = new dbCookingEntities();
            t建議食材 prod = db.t建議食材.FirstOrDefault(p => p.f建議食材Id == editfood.f建議食材Id);

            if (prod != null)
            {
                prod.f聚會Id = Convert.ToInt32(Request.Form["f聚會Id"]);
                prod.f食材名稱 = editfood.f食材名稱;
                prod.f數量 = editfood.f數量;
                prod.f單位 = editfood.f單位;

                db.SaveChanges();
            }

            return RedirectToAction("FoodList");


        }
        public ActionResult queryDelete_food(int id)
        {
            dbCookingEntities db = new dbCookingEntities();
            t建議食材 prod = db.t建議食材.FirstOrDefault(p => p.f建議食材Id == id);


            if (prod != null)
            {
                db.t建議食材.Remove(prod);
                db.SaveChanges();
            }

            return RedirectToAction("queryFoodList",new { id=prod.f聚會Id});

        }
        public ActionResult Delete_food(int id)
        {
            dbCookingEntities db = new dbCookingEntities();
            t建議食材 prod = db.t建議食材.FirstOrDefault(p => p.f建議食材Id == id);


            if (prod != null)
            {
                db.t建議食材.Remove(prod);
                db.SaveChanges();
            }
            return RedirectToAction("FoodList");

        }
        public ActionResult CreateFood()
        {
            dbCookingEntities db = new dbCookingEntities();

            int query主辦人id = ((t會員)Session[CSessionKey.登入會員_t會員]).f會員Id;
            var query聚會id = (from prod in db.t聚會
                             where prod.f主辦人 == query主辦人id
                             select prod.f聚會Id).Max();
            ViewBag.Boss = query主辦人id;
            ViewBag.Partyid = query聚會id;
            return View();
        }
        [HttpPost]
        public ActionResult CreateFood(CFoodViewModel query聚會food)
        {
            dbCookingEntities db = new dbCookingEntities();

            t建議食材 addfood = new t建議食材();

            addfood.f聚會Id = Convert.ToInt32(Request.Form["f聚會Id"]);
            addfood.f食材名稱 = query聚會food.f食材名稱;
            addfood.f數量 = Convert.ToInt32(query聚會food.f數量);
            addfood.f單位 = query聚會food.f單位;

            db.t建議食材.Add(addfood);

            db.SaveChanges();

            return RedirectToAction("FoodList");
        }
        public ActionResult FoodList()
        {

            dbCookingEntities db = new dbCookingEntities();

            int query主辦人id = ((t會員)Session[CSessionKey.登入會員_t會員]).f會員Id;
            var query聚會id = (from prod in db.t聚會
                             where prod.f主辦人 == query主辦人id
                             select prod.f聚會Id).Max();

            IEnumerable<t建議食材> datas = null;


            ViewBag.f聚會id = query聚會id;

            datas = from p in (new dbCookingEntities()).t建議食材
                    where p.f聚會Id == query聚會id
                    select p;

            List<CFoodViewModel> list = new List<CFoodViewModel>();

            foreach (t建議食材 p in datas)
                list.Add(new CFoodViewModel() { party_food = p });

            return View(list);

        }
        public ActionResult queryFoodList(int id)
        {
            int a = id;
            ViewBag.f聚會id = a;
            dbCookingEntities db = new dbCookingEntities();
            IEnumerable<t建議食材> datas = null;

            datas = from p in (new dbCookingEntities()).t建議食材
                    where p.f聚會Id == id
                    select p;

            List<CFoodViewModel> list = new List<CFoodViewModel>();

            foreach (t建議食材 p in datas)
                list.Add(new CFoodViewModel() { party_food = p });

            return View(list);

        }
       
    }
}

prjCooking/Views/Food/CreateFood.cshtml
@model prjCooking.ViewModel.CFoodViewModel

@{
    ViewBag.Title = "CreateFood";
}
<style>

    .timeFalse {
        color: crimson;
        font-size: 14px;
    }

    .timeTrue {
        color: darkcyan;
        font-size: 14px;
    }
</style>
<h2 class="text-info">舉辦共煮</h2>
<hr>
<br>
@using (Html.BeginForm("CreateFood", "Food",
    FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="container myfont1">
            <!-- 網站內容 -->


            <section>
                <div class="container ">
                    <div class="row">

                        <div class="col-md-6 offset-md-1 text-center bg-light">

                            <div class="row">
                                <aside class="col-6 text-left">
                                    <br>
                                    <h4 class="text-info">新增共煮食材:</h4>
                                </aside>
                                <aside class="col-6 text-right">
                                    <br />
                                    @Html.ActionLink("回到食材列表", "FoodList", null, new { @Class = "btn btn-sm btn-outline-secondary" })


                                </aside>


                                <aside class="col-12 text-left">

                                    <hr>
                                    <br>
                                    <input type="hidden" value="@ViewBag.Boss" name="txt_boss" />
                                    <input type="hidden" value="@ViewBag.Partyid" name="f聚會Id" />
                                </aside>

                                <aside class="form-group col-6 text-left">

                                    @Html.LabelFor(model => model.f食材名稱, htmlAttributes: new { @class = "control-label" })
                                    @Html.EditorFor(model => model.f食材名稱, new { htmlAttributes = new { @class = "form-control", name = "f食材名稱" ,id= "foodname" } })<span id="W_foodname"></span>
                                    @Html.ValidationMessageFor(model => model.f食材名稱, "", new { @class = "text-danger" })


                                </aside>
                                <aside class="form-group col-3 text-left">
                                    @Html.LabelFor(model => model.f數量, htmlAttributes: new { @class = "control-label" })
                                    @Html.EditorFor(model => model.f數量, new { htmlAttributes = new { @class = "form-control", name = "f數量", @type = "number" } })
                                    @Html.ValidationMessageFor(model => model.f數量, "", new { @class = "text-danger" })


                                </aside>
                                <aside class="form-group col-3 text-left">
                                    @Html.LabelFor(model => model.f單位, htmlAttributes: new { @class = "control-label" })
                                    @Html.EditorFor(model => model.f單位, new { htmlAttributes = new { @class = "form-control", name = "f食材名稱" } })
                                    @Html.ValidationMessageFor(model => model.f單位, "", new { @class = "text-danger" })

                                </aside>
                                <aside class="col-12 text-right">
                                    @Html.ActionLink("取消", "FoodList", null, new { Class = "btn btn-outline-info" })

                                    <input class="btn btn-outline-info" type="submit" value="儲存" >
                                  

                                </aside>
                                <aside class="col-12 text-right">
                                </aside>

                                <aside class="col-12 text-right">
                                    <br><hr>


                                    <br><br>
                                </aside>

                            </div>

                        </div>

                    </div>

                </div>
            </section>
            <br><br>

        </div>
    </div>


}
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script>
    document.getElementById("foodname").addEventListener("blur", chkfoodname);

    function chkfoodname() {

        let Ofoodname = document.getElementById("foodname");
        let OfoodnameVal = Ofoodname.value;
        let sp = document.getElementById("W_foodname");
        if (OfoodnameVal == "") {
            sp.innerHTML = "⛔ 食材名稱不可空白";
            document.getElementById("W_foodname").className = "timeFalse";

        } else {
            sp.innerHTML = "✔ 輸入正確";
            document.getElementById("W_foodname").className = "timeTrue";
        }

    }
</script>

prjCooking/Views/Food/EditFood.cshtml
@model prjCooking.ViewModel.CFoodViewModel

@{
    ViewBag.Title = "CreateFood";
}
<style>

    .timeFalse {
        color: crimson;
        font-size: 14px;
    }

    .timeTrue {
        color: darkcyan;
        font-size: 14px;
    }
</style>
<h2 class="text-info">舉辦共煮</h2>
<hr>
<br>
@using (Html.BeginForm("EditFood", "Food",
    FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="container myfont1">
            <!-- 網站內容 -->


            <section>
                <div class="container ">
                    <div class="row">

                        <div class="col-md-6 offset-md-1 text-center bg-light">

                            <div class="row">
                                <aside class="col-6 text-left">
                                    <br>
                                    <h4 class="text-info">編輯共煮食材:</h4>
                                </aside>
                                <aside class="col-6 text-right">
                                    <br>
                                    @Html.ActionLink("回到食材列表", "FoodList", null, new { @Class = "btn btn-sm btn-outline-secondary" })
                                </aside>


                                <aside class="col-12 text-left">

                                    <hr>
                                    <br>

                                    <input type="hidden" value="@Model.f聚會Id" name="f聚會Id" />
                                    <input type="hidden" value="@Model.f建議食材Id" name="f建議食材Id" />
                                </aside>

                                <aside class="form-group col-6 text-left">

                                    @Html.LabelFor(model => model.f食材名稱, htmlAttributes: new { @class = "control-label" })
                                    @Html.EditorFor(model => model.f食材名稱, new { htmlAttributes = new { @class = "form-control", name = "f食材名稱", id = "foodname" } })<span id="W_foodname"></span>
                                    @Html.ValidationMessageFor(model => model.f食材名稱, "", new { @class = "text-danger" })


                                </aside>
                                <aside class="form-group col-3 text-left">
                                    @Html.LabelFor(model => model.f數量, htmlAttributes: new { @class = "control-label" })
                                    @Html.EditorFor(model => model.f數量, new { htmlAttributes = new { @class = "form-control", name = "f數量", @type = "number" } })
                                    @Html.ValidationMessageFor(model => model.f數量, "", new { @class = "text-danger" })


                                </aside>
                                <aside class="form-group col-3 text-left">
                                    @Html.LabelFor(model => model.f單位, htmlAttributes: new { @class = "control-label" })
                                    @Html.EditorFor(model => model.f單位, new { htmlAttributes = new { @class = "form-control", name = "f食材名稱" } })
                                    @Html.ValidationMessageFor(model => model.f單位, "", new { @class = "text-danger" })

                                </aside>
                                <aside class="col-12 text-right">


                                    <input class="btn btn-outline-info" type="submit" value="儲存">


                                </aside>
                                <aside class="col-12 text-right">
                                </aside>

                                <aside class="col-12 text-right">
                                    <br><hr>


                                    <br><br>
                                </aside>

                            </div>

                        </div>

                    </div>

                </div>
            </section>
            <br><br>

        </div>
    </div>


}
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script>
    document.getElementById("foodname").addEventListener("blur", chkfoodname);

    function chkfoodname() {

        let Ofoodname = document.getElementById("foodname");
        let OfoodnameVal = Ofoodname.value;
        let sp = document.getElementById("W_foodname");
        if (OfoodnameVal == "") {
            sp.innerHTML = "⛔ 食材名稱不可空白";
            document.getElementById("W_foodname").className = "timeFalse";

        } else {
            sp.innerHTML = "✔ 輸入正確";
            document.getElementById("W_foodname").className = "timeTrue";
        }

    }
</script>

prjCooking/Views/Food/FoodList.cshtml
@model IEnumerable<prjCooking.ViewModel.CFoodViewModel>


@{
    ViewBag.Title = "FoodList";
}


<section class="service-wrapper py-7">
    <div class="service-tag py-5 bg-white">
    </div>
</section>
<div class="container myfont1">
    <!-- 網站內容 -->



    <section class="">

        <div class="container ">
            <div class="row">
                <div class="col-md-6 offset-md-1 text-center bg-light">
                    <br />
                    <div class="row">

                        <aside class="col-6 text-left">
                            <h4 class="text-info ">共煮食材列表</h4>
                            <input type="hidden" value="@ViewBag.f聚會id" name="f聚會id" />
                        </aside>
                        <aside class="col-6 text-right">

                            @Html.ActionLink("新增食材", "CreateFood", null, new { @class = "btn btn-outline-info" })
                        </aside>
                        <aside class="col-12 text-left">
                            <hr /><br />
                        </aside>

                        <aside class="col-12">

                            <table class="table table-condensed table-hover table-responsive">
                                <thead>
                                <th>
                                    編號
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.f食材名稱)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.f數量)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.f單位)
                                </th>

                                <th></th>
                                </thead>

                                @{ int count = 0;
                                    foreach (var item in Model)
                                    {
                                        count++;

                                        <tr>
                                            <td>
                                                @count
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.f食材名稱)

                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.f數量)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.f單位)
                                            </td>

                                            <td>
                                                @Html.ActionLink("✎", "EditFood", new { id = item.f建議食材Id }, new { @class = "btn btn-outline-secondary" })
                                                <input type="button" value="✘" class="btn btn-outline-secondary" data-toggle="modal" data-target="#modalone" />
                                                <div class="modal" id="modalone">
                                                    <div class="modal-md modal-dialog modal-dialog-scrollable">

                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <i class="modal-title text-danger bi bi-exclamation-circle"></i>
                                                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                            </div>
                                                            <div class="modal-body">
                                                                <p>確定要刪除嗎?</p>

                                                            </div>
                                                            <div class="modal-footer">
                                                                <input type="button" value="取消" class="btn btn-sm btn-outline-info" data-dismiss="modal">
                                                                @Html.ActionLink("確定", "Delete_food", new { id = item.f建議食材Id }, new { @class = "btn btn-sm btn-outline-info" })

                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <!-- 編輯資訊結束 -->



                                            </td>
                                        </tr>
                                    }
                                }
                            </table>
                        </aside>
                        
                        <aside class="col-12 text-right">
                            @Html.ActionLink("完成", "Index", "Home", null, new { Class = "btn btn-sm btn-outline-secondary" })
                            <br /><br />
                        </aside>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <br /><br />

</div>

prjCooking/Views/Food/queryCreateFood.cshtml
@model prjCooking.ViewModel.CFoodViewModel

@{
    ViewBag.Title = "CreateFood";
}
<style>

    .timeFalse {
        color: crimson;
        font-size: 14px;
    }

    .timeTrue {
        color: darkcyan;
        font-size: 14px;
    }
</style>
<h2 class="text-info">舉辦共煮</h2>
<hr>
<br>
@using (Html.BeginForm("queryCreateFood", "Food",
    FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="container myfont1">
            <!-- 網站內容 -->


            <section>
                <div class="container ">
                    <div class="row">

                        <div class="col-md-6 offset-md-1 text-center bg-light">

                            <div class="row">
                                <aside class="col-6 text-left">
                                    <br>
                                    <h4 class="text-info">新增共煮食材:</h4>
                                </aside>
                                <aside class="col-6 text-right">
                                    <br />
                                    @Html.ActionLink("回到食材列表", "queryFoodList", new { id = @ViewBag.Partyid }, new { @Class = "btn btn-sm btn-outline-secondary" })


                                </aside>


                                <aside class="col-12 text-left">

                                    <hr>
                                    <br>
                                    <input type="hidden" value="@ViewBag.Boss" name="txt_boss" />
                                    <input type="hidden" value="@ViewBag.Partyid" name="f聚會Id" />
                                </aside>

                                <aside class="form-group col-6 text-left">

                                    @Html.LabelFor(model => model.f食材名稱, htmlAttributes: new { @class = "control-label" })
                                    @Html.EditorFor(model => model.f食材名稱, new { htmlAttributes = new { @class = "form-control", name = "f食材名稱",id="foodname"} })<span id="W_foodname"></span>
                                    @Html.ValidationMessageFor(model => model.f食材名稱, "", new { @class = "text-danger" })


                                </aside>
                                <aside class="form-group col-3 text-left">
                                    @Html.LabelFor(model => model.f數量, htmlAttributes: new { @class = "control-label" })
                                    @Html.EditorFor(model => model.f數量, new { htmlAttributes = new { @class = "form-control", name = "f數量", @type = "number" } })
                                    @Html.ValidationMessageFor(model => model.f數量, "", new { @class = "text-danger" })


                                </aside>
                                <aside class="form-group col-3 text-left">
                                    @Html.LabelFor(model => model.f單位, htmlAttributes: new { @class = "control-label" })
                                    @Html.EditorFor(model => model.f單位, new { htmlAttributes = new { @class = "form-control", name = "f食材名稱" } })
                                    @Html.ValidationMessageFor(model => model.f單位, "", new { @class = "text-danger" })

                                </aside>
                                <aside class="col-12 text-right">
                                    @Html.ActionLink("取消", "queryFoodList", new { id = @ViewBag.Partyid }, new { Class = "btn btn-outline-info" })

                                    <input class="btn btn-outline-info" type="submit" value="儲存">
                                   

                                </aside>
                                <aside class="col-12 text-right">
                                </aside>

                                <aside class="col-12 text-right">
                                    <br><hr>


                                    <br><br>
                                </aside>

                            </div>

                        </div>

                    </div>

                </div>
            </section>
            <br><br>

        </div>
    </div>


}
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script>
    document.getElementById("foodname").addEventListener("blur", chkfoodname);

    function chkfoodname() {

        let Ofoodname = document.getElementById("foodname");
        let OfoodnameVal = Ofoodname.value;
        let sp = document.getElementById("W_foodname");
        if (OfoodnameVal == "") {
            sp.innerHTML = "⛔ 食材名稱不可空白";
            document.getElementById("W_foodname").className = "timeFalse";

        } else {
            sp.innerHTML = "✔ 輸入正確";
            document.getElementById("W_foodname").className = "timeTrue";
        }

    }
</script>

prjCooking/Views/Food/queryEditFood.cshtml
@model prjCooking.ViewModel.CFoodViewModel

@{
    ViewBag.Title = "CreateFood";
}
<style>

    .timeFalse {
        color: crimson;
        font-size: 14px;
    }

    .timeTrue {
        color: darkcyan;
        font-size: 14px;
    }
</style>
<h2 class="text-info">舉辦共煮</h2>
<hr>
<br>
@using (Html.BeginForm("queryEditFood", "Food",
    FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="container myfont1">
            <!-- 網站內容 -->


            <section>
                <div class="container ">
                    <div class="row">

                        <div class="col-md-6 offset-md-1 text-center bg-light">

                            <div class="row">
                                <aside class="col-6 text-left">
                                    <br>
                                    <h4 class="text-info">編輯共煮食材:</h4>
                                </aside>
                                <aside class="col-6 text-right">
                                    <br>
                                    @Html.ActionLink("回到食材列表", "queryFoodList", new { id = Model.f聚會Id }, new { @Class = "btn btn-sm btn-outline-secondary" })
                                </aside>

                                <aside class="col-12 text-left">

                                    <hr>
                                    <br>

                                    <input type="hidden" value="@Model.f聚會Id" name="f聚會Id" />
                                    <input type="hidden" value="@Model.f建議食材Id" name="f建議食材Id" />
                                </aside>

                                <aside class="form-group col-6 text-left">

                                    @Html.LabelFor(model => model.f食材名稱, htmlAttributes: new { @class = "control-label" })
                                    @Html.EditorFor(model => model.f食材名稱, new { htmlAttributes = new { @class = "form-control", name = "f食材名稱", id = "foodname" } })<span id="W_foodname"></span>
                                    @Html.ValidationMessageFor(model => model.f食材名稱, "", new { @class = "text-danger" })


                                </aside>
                                <aside class="form-group col-3 text-left">
                                    @Html.LabelFor(model => model.f數量, htmlAttributes: new { @class = "control-label" })
                                    @Html.EditorFor(model => model.f數量, new { htmlAttributes = new { @class = "form-control", name = "f數量", @type = "number" } })
                                    @Html.ValidationMessageFor(model => model.f數量, "", new { @class = "text-danger" })


                                </aside>
                                <aside class="form-group col-3 text-left">
                                    @Html.LabelFor(model => model.f單位, htmlAttributes: new { @class = "control-label" })
                                    @Html.EditorFor(model => model.f單位, new { htmlAttributes = new { @class = "form-control", name = "f食材名稱" } })
                                    @Html.ValidationMessageFor(model => model.f單位, "", new { @class = "text-danger" })

                                </aside>
                                <aside class="col-12 text-right">


                                    <input class="btn btn-outline-info" type="submit" value="儲存" data-toggle="modal" data-target="#modalone">


                                </aside>
                                <aside class="col-12 text-right">
                                </aside>

                                <aside class="col-12 text-right">
                                    <br><hr>


                                    <br><br>
                                </aside>

                            </div>

                        </div>

                    </div>

                </div>
            </section>
            <br><br>

        </div>
    </div>


}
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script>
    document.getElementById("foodname").addEventListener("blur", chkfoodname);

    function chkfoodname() {

        let Ofoodname = document.getElementById("foodname");
        let OfoodnameVal = Ofoodname.value;
        let sp = document.getElementById("W_foodname");
        if (OfoodnameVal == "") {
            sp.innerHTML = "⛔ 食材名稱不可空白";
            document.getElementById("W_foodname").className = "timeFalse";

        } else {
            sp.innerHTML = "✔ 輸入正確";
            document.getElementById("W_foodname").className = "timeTrue";
        }

    }
</script>