prjCooking/Controllers/MeetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using prjCooking.Models;
using prjCooking.ViewModel;
using PagedList;

namespace prjCooking.Controllers
{
    public class MeetController : Controller
    {
        // GET: Meet
       
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult add主辦人影片(int 聚會Id, string f主辦人URL)
        {

            dbCookingEntities db = new dbCookingEntities();
            t聚會 Addparty = db.t聚會.FirstOrDefault(p => p.f聚會Id == 聚會Id);
            if (Addparty != null)
            {
                Addparty.f主辦人影片URL = f主辦人URL;
                db.SaveChanges();
            }
            return RedirectToAction("showParty", new { id = 聚會Id });
        }
        public ActionResult Party_Reported(int 檢舉聚會Id,string f檢舉原因)
        {
            dbCookingEntities db = new dbCookingEntities();
            t檢舉 Wprob = new t檢舉();
            
            Wprob.f被檢舉的聚會Id = 檢舉聚會Id;
            Wprob.f檢舉人Id= ((t會員)Session[CSessionKey.登入會員_t會員]).f會員Id;
            Wprob.f檢舉建立日期 = DateTime.Now;
            Wprob.f檢舉原因 = f檢舉原因;
            
            db.t檢舉.Add(Wprob);
            db.SaveChanges();
            
            return RedirectToAction("showParty", new { id = 檢舉聚會Id });
        }
        public ActionResult Edit_party(int id, int party_boss)
        {

            dbCookingEntities db = new dbCookingEntities();
            t聚會 prod = db.t聚會.FirstOrDefault(p => p.f聚會Id == id);
            t會員 prod_boss = db.t會員.FirstOrDefault(p => p.f會員Id == party_boss);
            string a = prod.f聚會日期.ToString("yyyy-MM-dd");
            string b = prod.f聚會開始時間.ToString("HH:mm");
            string c = prod.f聚會結束時間.Value.ToString("HH:mm");
            ViewBag.聚會id = id;
            ViewBag.partydate = a;
            ViewBag.partystart = b;
            ViewBag.partyend = c;
            if (prod == null)
                return RedirectToAction("showParty");
            CPartyViewModel select_party = new CPartyViewModel() { party = prod, party_boss = prod_boss };


            return View(select_party);

        }
        [HttpPost]
        public ActionResult Edit_party(CPartyViewModel newparty,string f聚會日期,string 聚會開始時間,string 聚會結束時間,int f聚會id)
        {
            dbCookingEntities db = new dbCookingEntities();
            t聚會 Addparty = db.t聚會.FirstOrDefault(p => p.f聚會Id == f聚會id);

            if (Addparty != null)
            {
                Addparty.f聚會Id = f聚會id;
                Addparty.f聚會名稱 = newparty.f聚會名稱;
                Addparty.f聚會內容 = newparty.f聚會內容;
                Addparty.f聚會關鍵字 = newparty.f聚會關鍵字;
                Addparty.f聚會軟體 = newparty.f聚會軟體;
                Addparty.f聚會軟體URL = newparty.f聚會軟體URL;
                Addparty.f聚會日期 = Convert.ToDateTime(f聚會日期);
                Addparty.f名額 = Convert.ToInt32(newparty.f名額);
                Addparty.f聚會通訊軟體 = newparty.f聚會通訊軟體;
                Addparty.f聚會通訊軟體帳號 = newparty.f聚會通訊軟體帳號;
                Addparty.f聚會垃圾桶 = false;
                Addparty.f聚會建立日期 = DateTime.Now;
                Addparty.f聚會開始時間 = Convert.ToDateTime(f聚會日期 + " " + 聚會開始時間);
                Addparty.f聚會結束時間 = Convert.ToDateTime(f聚會日期 + " " + 聚會結束時間);

                if (Addparty.f聚會開始時間 > DateTime.Now)
                    Addparty.f聚會狀態 = Convert.ToInt32(聚會狀態.可報名);
                else if ((Addparty.f聚會開始時間 < DateTime.Now) && (Addparty.f聚會結束時間 > DateTime.Now))
                    Addparty.f聚會狀態 = Convert.ToInt32(聚會狀態.進行中);
                else
                    Addparty.f聚會狀態 = Convert.ToInt32(聚會狀態.已結束);

                if (newparty.image != null)
                {
                    //把照片重新命名
                    //讓名稱為唯一值
                    string photoName = Guid.NewGuid().ToString() + ".jpg";
                    Addparty.f聚會照片 = photoName;
                    newparty.image.SaveAs(Server.MapPath("~/image/" + photoName));

                }
                

                db.SaveChanges();
            }
         

            return RedirectToAction("showParty", new{id= newparty.f聚會Id});
        }
        public ActionResult showParty(int? id)
        {
            if (id.HasValue)
            {
                C聚會資訊For頁面ViewModel vmodel = (new C聚會相關操作()).撈取單一聚會資訊(id.Value);

                if(vmodel != null)
                {
                    if (Session[CSessionKey.登入會員_t會員] != null)
                        vmodel.當前登入會員資訊 = (t會員)Session[CSessionKey.登入會員_t會員];
                    else
                    {
                        vmodel.當前登入會員資訊 = new t會員();
                        vmodel.當前登入會員資訊.f會員Id = 0;
                    }

                    vmodel.參加者資訊List.Reverse();
                    foreach (C參加者資訊For聚會頁面 參加者 in vmodel.參加者資訊List)
                    {
                        if (參加者.參加者資訊.f會員Id == vmodel.當前登入會員資訊.f會員Id)
                        {
                            vmodel.當前會員參加者Id = 參加者.參加者資料.f參加者Id;
                            if(!參加者.參加者資料.f報名)
                                vmodel.Is當前會員報名 = true;
                            if (參加者.評論 != null)
                                vmodel.Is成果發表 = true;
                            if (參加者.參加者資料.f審核狀態)
                                vmodel.Is核准參與 = true;

                            break;
                        }
                    }

                    return View(vmodel);
                }
            }

            return RedirectToAction("Index", "Home");
        }

        public ActionResult CreateParty()
        {
          
            if (Session[CSessionKey.登入會員_t會員] != null)
            {
                ViewBag.email = ((t會員)Session[CSessionKey.登入會員_t會員]).f會員信箱;

                return View();
            }
            return RedirectToAction("登入", "Member");

        }

        [HttpPost]
        public ActionResult CreateParty(CPartyViewModel newparty)
        {
            dbCookingEntities db = new dbCookingEntities();
            t聚會 Addparty = new t聚會();

            Addparty.f主辦人 = ((t會員)Session[CSessionKey.登入會員_t會員]).f會員Id;
            Addparty.f聚會名稱 = newparty.f聚會名稱;
            Addparty.f聚會內容 = newparty.f聚會內容;
            Addparty.f聚會關鍵字 = newparty.f聚會關鍵字;
            Addparty.f聚會軟體 = newparty.f聚會軟體;
            Addparty.f聚會軟體URL = newparty.f聚會軟體URL;
            Addparty.f聚會日期 = Convert.ToDateTime(newparty.f聚會日期);
            Addparty.f名額 = Convert.ToInt32(newparty.f名額);
            Addparty.f聚會通訊軟體 = newparty.f聚會通訊軟體;
            Addparty.f聚會通訊軟體帳號 = newparty.f聚會通訊軟體帳號;
            Addparty.f聚會垃圾桶 = false;
            Addparty.f聚會建立日期 = DateTime.Now;
            Addparty.f聚會開始時間 = Convert.ToDateTime(newparty.f聚會日期 + " " + newparty.f聚會開始時間);
            Addparty.f聚會結束時間 = Convert.ToDateTime(newparty.f聚會日期 + " " + newparty.f聚會結束時間);

            if (Addparty.f聚會開始時間 > DateTime.Now)
                Addparty.f聚會狀態 = Convert.ToInt32(聚會狀態.可報名);
            else if ((Addparty.f聚會開始時間 < DateTime.Now) && (Addparty.f聚會結束時間 > DateTime.Now))
                Addparty.f聚會狀態 = Convert.ToInt32(聚會狀態.進行中);
            else
                Addparty.f聚會狀態 = Convert.ToInt32(聚會狀態.已結束);

            if (newparty.image != null)
            {
                //把照片重新命名
                //讓名稱為唯一值
                string photoName = Guid.NewGuid().ToString() + ".jpg";
                Addparty.f聚會照片 = photoName;
                newparty.image.SaveAs(Server.MapPath("~/image/" + photoName));

            }
            else
                Addparty.f聚會照片 = "party_02.jpg";
            
            
            db.t聚會.Add(Addparty);
            db.SaveChanges();

            
            return RedirectToAction("CreateFood", "Food");
        }
        public ActionResult 報名紀錄(int? sort = 0, int? statu = 3, int page = 1)
        {
            // 排序 0新 1舊
            // 狀態 3 全部
            if(Session[CSessionKey.登入會員_t會員] != null)
            {
                // session取得會員資料
                int 會員Id = ((t會員)Session[CSessionKey.登入會員_t會員]).f會員Id;
                CCaptureRecords crs = new CCaptureRecords();
                C主辦Or報名ViewModel vmodel = new C主辦Or報名ViewModel();
                List<CCaptureMeetInfo> data = crs.撈取報名記錄(會員Id, sort, statu);
                vmodel.Info = crs.GetPageList(data, page);

                if (sort != null && statu != null) 
                {
                    vmodel.CurrentSort = sort.ToString();
                    vmodel.CurrentStatu = statu.ToString();
                }
                
                return View(vmodel);
            }

            return RedirectToAction("Index", "Home");
        }

        public ActionResult 主辦紀錄(int? sort = 0, int page = 1)
        {
            if (Session[CSessionKey.登入會員_t會員] != null)
            {
                int 會員Id = ((t會員)Session[CSessionKey.登入會員_t會員]).f會員Id;
                CCaptureRecords crs = new CCaptureRecords();
                C主辦Or報名ViewModel vmodel = new C主辦Or報名ViewModel();
                List<CCaptureMeetInfo> data = crs.撈取主辦記錄(會員Id, sort);
                vmodel.Info = crs.GetPageList(data, page);

                if (sort != null)
                {
                    vmodel.CurrentSort = sort.ToString();
                }

                return View(vmodel);
            }

            return RedirectToAction("Index", "Home");
        }

        public ActionResult 資格審核(int? meetId)
        {
            // 判斷Session
            if(Session[CSessionKey.登入會員_t會員] != null)
            {
                if(meetId != null)
                {
                    C資格審核ViewModel vmodel = new C資格審核ViewModel();
                    C撈取資格審核名單 撈取 = new C撈取資格審核名單();
                    int 主辦人Id = ((t會員)Session[CSessionKey.登入會員_t會員]).f會員Id;
                    vmodel.當前聚會 = (new dbCookingEntities()).Cooking查詢某聚會資訊By聚會Id(meetId.Value);

                    // 撈取已核准名單
                    bool 核准 = Convert.ToBoolean(參加者審核狀態.通過);
                    if (撈取.Set撈取(主辦人Id, meetId, 核准))

prjCooking/Views/Meet/CreateParty.cshtml
@using prjCooking.Models
@model prjCooking.ViewModel.CPartyViewModel



@{
    ViewBag.Title = "新增聚會";
}
<style>

    .timeFalse {
        color: crimson;
        font-size: 14px;
    }

    .timeTrue {
        color: darkcyan;
        font-size: 14px;
    }

</style>

<h2 class="text-info">舉辦共煮</h2>
<hr>
<br>

@using (Html.BeginForm("CreateParty", "Meet",
    FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="container">
            <div class="row">

                <div class="col-md-7 offset-md-2 text-center bg-light">

                    <div class="row">

                        <div class="form-group col-md-12 text-left">
                            <br>
                            <!-- 照片 -->
                            <img src="~/Image/party_02.jpg" id="imgpreview" class="card-img" name="f聚會照片">
                            <br><br>
                            <input type="file" name="image" id="fileupload" accept="image/jpeg, image/gif, image/png" onchange="openFile()" multiple>
                            <br>
                            <!-- 照片結束 -->
                            <hr>
                        </div>
                    
                        <div class="form-group col-12 text-left">
                            <label><span class="text-danger">*</span>聚會名稱</label>

                            @Html.EditorFor(model => model.f聚會名稱, new { htmlAttributes = new { @class = "form-control", placeholder = "請輸入聚會名稱", name = "f聚會名稱" } })
                            @Html.ValidationMessageFor(model => model.f聚會名稱, "", new { @class = "text-danger" })
                        </div>
                               <div class="form-group col-12 text-left">
                                   <label>請介紹您的共煮聚會:</label> 
                               
                                   @Html.EditorFor(model => model.f聚會內容, new { htmlAttributes = new { @class = "form-control", placeholder = "", name = "f聚會內容" } })
                                   @Html.ValidationMessageFor(model => model.f聚會內容, "", new { @class = "text-danger" })
                                 
                               </div>

                    
                 
                        <div class="form-group col-12 text-left">
                            <label>關鍵字<span class="text-danger">(請在每個關鍵字前加上#)</span></label>
                            @Html.EditorFor(model => model.f聚會關鍵字, new { htmlAttributes = new { @class = "form-control", placeholder = "請在每個關鍵字前加上#", name = "f聚會關鍵字", id = "txt_tag" } })<span id="W_tag"></span>
                            @Html.ValidationMessageFor(model => model.f聚會關鍵字, "", new { @class = "text-danger" })
                        </div>


                        <div class="form-group col-12 text-left">
                            <label> <span class="text-danger">*</span>聚會平台</label>
                            @Html.EditorFor(model => model.f聚會軟體, new { htmlAttributes = new { @class = "form-control", placeholder = "請輸入平台名稱", name = "f聚會軟體" } })
                            @Html.ValidationMessageFor(model => model.f聚會軟體, "", new { @class = "text-danger" })
                        </div>

                  
                        <div class="form-group col-12 text-left">
                            <label><span class="text-danger">*</span>聚會連結</label>

                            @Html.EditorFor(model => model.f聚會軟體URL, new { htmlAttributes = new { @class = "form-control", placeholder = "請輸入平台連結", name = "f聚會軟體URL" } })
                            @Html.ValidationMessageFor(model => model.f聚會軟體URL, "", new { @class = "text-danger" })
                        </div>
              
                        <div class="form-group col-12 text-left">
                            <label><span class="text-danger">*</span>舉辦日期</label>
                      
                            @Html.EditorFor(model => model.f聚會日期, new { htmlAttributes = new { @class = "form-control", @type = "date", style = "width:60%", name = "f聚會日期", id = "txt_date" } })<span id="W_date"></span>
                            @Html.ValidationMessageFor(model => model.f聚會日期, "", new { @class = "text-danger" })
                        </div>
                
                        <div class="form-group col-12 text-left">
                            <label><span class="text-danger">*</span>開始時間</label>
                            @Html.EditorFor(model => model.f聚會開始時間, new { htmlAttributes = new { @class = "form-control", @type = "time", style = "width:60%", name = "f聚會開始時間", id = "txt_starttime" } })
                            @Html.ValidationMessageFor(model => model.f聚會開始時間, "", new { @class = "text-danger" })
                        </div>

                  
                        <div class="form-group col-12 text-left">
                            <label><span class="text-danger">*</span>結束時間</label>
                        
                            @Html.EditorFor(model => model.f聚會結束時間, new { htmlAttributes = new { @class = "form-control", @type = "time", style = "width:60%", name = "f聚會結束時間", id = "txt_endtime" } })<span id="W_endtime"></span>
                            @Html.ValidationMessageFor(model => model.f聚會結束時間, "", new { @class = "text-danger" })
                        </div>
                  
                        <div class="form-group col-12 text-left">
                            <label><span class="text-danger">*</span>名額<span class="text-danger">(只能輸入數字)</span></label>
                            @Html.EditorFor(model => model.f名額, new { htmlAttributes = new { @class = "form-control", @type = "number", placeholder = "", style = "width:25%", name = "f名額" } })
                            @Html.ValidationMessageFor(model => model.f名額, "", new { @class = "text-danger" })

                        </div>
                  
                        <div class="col-12 text-left">
                            <hr>
                            <p>煮辦人聯絡資訊:</p>
                            <p class="text-danger">以下內容僅提供給審核成功的共煮成員</p>
                        </div>

                        <!-- 煮辦人聯絡資訊 -->

                        <br /><br />

                        <div class="form-group col-12 text-left">
                            <p>信箱:</p>
                        
                            <input type="text" class="form-control" placeholder="" value="@ViewBag.email " disabled>
                        </div>

                        <div class="form-group col-12 text-left">
                            @Html.LabelFor(model => model.f聚會通訊軟體, htmlAttributes: new { @class = "control-label" })
    
                            @Html.EditorFor(model => model.f聚會通訊軟體, new { htmlAttributes = new { @class = "form-control", name = "f聚會通訊軟體" } })
                            @Html.ValidationMessageFor(model => model.f聚會通訊軟體, "", new { @class = "text-danger" })
                           
                        </div>

                        <div class="form-group col-12 text-left">
                            @Html.LabelFor(model => model.f聚會通訊軟體帳號, htmlAttributes: new { @class = "control-label" })

                            @Html.EditorFor(model => model.f聚會通訊軟體帳號, new { htmlAttributes = new { @class = "form-control", name = "f聚會通訊軟體帳號" } })
                            @Html.ValidationMessageFor(model => model.f聚會通訊軟體帳號, "", new { @class = "text-danger" })

                        </div>

                        <div class="col-12 text-right">
                           <hr>

                            <input type="button" value="發布" class="btn btn-outline-info" data-toggle="modal" data-target="#modalone" />
                            <br><br>
                            <div class="modal text-center" id="modalone">
                                <div class="modal-md modal-dialog modal-dialog-scrollable">

                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <img src="~/Image/heart.svg" class="modal-title">
                                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                                        </div>
                                        <div class="modal-body">
                                            <p>確定要發布嗎?</p>

                                        </div>
                                        <div class="modal-footer">
                                            <input type="button" value="取消" class="btn btn-sm btn-outline-info" data-dismiss="modal">

                                            <input type="submit" value="確定" class="btn btn-sm btn-outline-info">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>

                </div>

            </div>

        </div>
    </div>
}



<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script>
    function openFile() {

        var fileUpload = document.getElementById("fileupload");
        var imgPreview = document.getElementById("imgpreview");
        var imgOne = fileUpload.files[0];

        if (fileUpload.files.length > 0) {

            var reader = new FileReader();

            reader.onload = function () {
                imgPreview.src = reader.result;
            };

            imgPreview.onload = function () {

            }

            reader.readAsDataURL(imgOne);

        } else {

        }
    }
</script>
<script>
    document.getElementById("txt_endtime").addEventListener("blur", chktime);
    function chktime() {
        let starttime = document.getElementById("txt_starttime");
        let endtime = document.getElementById("txt_endtime");
        let starttimeVal = starttime.value;
        let endtimeVal = endtime.value;
        let sp = document.getElementById("W_endtime");

        if (endtimeVal == " ") {
            sp.innerHTML = "⛔ 結束時間不可空白"
            document.getElementById("W_endtime").className = "timeFalse";
        }
        else if (endtimeVal <= starttimeVal) {
            sp.innerHTML = "⛔ 結束時間需大於開始時間";
            document.getElementById("W_endtime").className = "timeFalse";
        } else {
            sp.innerHTML = "✔ 輸入正確";
            document.getElementById("W_endtime").className = "timeTrue";
        }
    }
    //判斷日期大於今日
    var d = new Date();
    var month = d.getMonth() + 1;
    var day = d.getDate();

    var output = d.getFullYear() + '-' +
        (month < 10 ? '0' : '') + month + '-' +
        (day < 10 ? '0' : '') + day;
    document.getElementById("txt_date").addEventListener("blur", chkdate);
    function chkdate() {
        let party_date = document.getElementById("txt_date");
        let party_dateVal = party_date.value;
        let sp = document.getElementById("W_date");

        console.log(party_dateVal);
        console.log(output);

        if (party_dateVal < output) {

            sp.innerHTML = "⛔ 聚會時間需大於等於今日";
            document.getElementById("W_date").className = "timeFalse";
        } else {
            sp.innerHTML = "✔ 輸入正確";
            document.getElementById("W_date").className = "timeTrue";
        }
    }

</script>
<script>
    //驗證關鍵字第一個字是#
    document.getElementById("txt_tag").addEventListener("blur", chktime);
    function chktime() {
        let tag = document.getElementById("txt_tag");
        let tagVal = tag.value;
        let tagValLen = tagVal.length;
        let sp = document.getElementById("W_tag");
        
        console.log(tagVal.substr(0,1));

        if (tagVal != null) {
            if (tagVal.substr(0, 1) == "#") {
                sp.innerHTML = "✔ 輸入正確";
                document.getElementById("W_tag").className = "timeTrue";

            } else {
                sp.innerHTML = "⛔ 關鍵字前面需加上#";
                document.getElementById("W_tag").className = "timeFalse";
            }
        }
    }
</script>

prjCooking/Views/Meet/資格審核.cshtml
@using prjCooking.ViewModel
@using prjCooking.Models
@model C資格審核ViewModel

@{
    ViewBag.Title = "資格審核";
}

<div class="service-tag py-5 bg-white">
    <!-- 資格審核 標體 -->
    <section class="row d-flex text-center mt-5">
        <hgroup class="col">
            <h2>@Model.當前聚會.f聚會名稱 - 資格審核</h2>
        </hgroup>
    </section>
    <!-- end 資格審核 標體 -->
    <!-- 資格審核 主體 -->
    <section class="row">
        <!-- 分頁導覽 -->
        <nav class="col mt-3">
            <ul class="nav nav-tabs justify-content-center">
                <li class="nav-item" role="presentation">
                    <a class="nav-link active" id="pass-tab" data-toggle="tab" data-target="#pass" type="button" role="tab" aria-controls="pass" aria-selected="true">已核准</a>
                </li>
                <li class="nav-item" role="presentation">
                    <a class="nav-link" id="nopass-tab" data-toggle="tab" data-target="#nopass" type="button" role="tab" aria-controls="nopass" aria-selected="false">未審核&nbsp;<span class="badge badge-danger">@Model.未審核.Count</span></a>
                </li>
            </ul>
            <div class="tab-content">
                <!-- 核准 內容 -->
                <div class="tab-pane fade show active" id="pass" role="tabpanel" aria-labelledby="pass-tab">
                    <!-- 核准後的會員陳列 -->
                    <section class="row">
                        @{
                            foreach (C審核參加者資訊 info in Model.核准)
                            {
                                <!-- 一筆會員資料 -->
                                <div class="col-6 col-md-3 pt-3">
                                    <div class="card h-100">
                                        @if (info.會員照片 != "")
                                        {
                                            <!-- Product image-->
                                            <img class="card-img-top" src="~/image/@info.會員照片" alt="@info.會員姓名" />
                                            <!-- Product details-->
                                        }
                                        <div class="card-body p-4">
                                            <div class="text-center">
                                                <!-- Product name-->
                                                <h5>@info.會員姓名</h5>
                                            </div>
                                        </div>
                                        <!-- Product actions-->
                                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                            <div class="text-center">
                                                @Html.ActionLink(
                                                   "檢視",
                                                   "Show個人頁面",
                                                   "Member",
                                                   new { id = info.參加者Id },
                                                   new { @class = "btn btn-outline-info mt-auto" })
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- end 一筆會員資料 -->
                            }
                        }
                    </section>
                    <!-- end 核准後的會員陳列 -->
                </div>
                <!-- end 核准 內容 -->
                <!-- 未審核 內容 -->
                <div class="tab-pane fade" id="nopass" role="tabpanel" aria-labelledby="nopass-tab">
                    <!-- 未審核的會員陳列 -->
                    <section class="row">
                        @{
                            foreach (C審核參加者資訊 info in Model.未審核)
                            {
                                <!-- 一筆會員資料 -->
                                <div class="col-6 col-md-3 pt-3">
                                    <div class="card h-100">
                                        @if (info.會員照片 != "")
                                        {
                                            <!-- Product image-->
                                            <img class="card-img-top" src="~/image/@info.會員照片" alt="@info.會員姓名" />
                                            <!-- Product details-->
                                        }
                                        <div class="card-body p-4">
                                            <div class="text-center">
                                                <!-- Product name-->
                                                <h5>@info.會員姓名</h5>
                                            </div>
                                        </div>
                                        <!-- Product actions-->
                                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                            <div class="text-center">
                                                @Html.ActionLink(
                                                   "檢視",
                                                   "Show個人頁面",
                                                   "Member",
                                                   new { id = info.參加者Id },
                                                   new { @class = "btn btn-outline-info mt-auto" })
                                                @if (Model.核准.Count < Model.當前聚會.f名額.Value)
                                                {
                                                    <br>
                                                    @Html.ActionLink(
                                                       "核准",
                                                       "核准參加者",
                                                       new { 聚會Id = info.聚會Id, 參加者Id = info.參加者Id },
                                                       new { @class = "btn btn-outline-primary my-2" })
                                                }
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- end 一筆會員資料 -->
                            }
                        }
                    </section>
                    <!-- end 未審核的會員陳列 -->
                </div>
                <!-- end 未審核 內容 -->
            </div>
        </nav>
        <!-- end 分頁導覽 -->
    </section>
    <!-- end 資格審核 主體 -->
</div>